/**
 * npm run seed
 *
 * Pushes the fictional seed dataset (src/lib/data/seed-data.ts) into a real
 * Supabase project. Only useful once you've set DEMO_MODE=false and
 * configured NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY - without
 * those, the app already runs against the same seed data in-memory (see
 * src/lib/data/memory-store.ts) and this script has nothing to do.
 */
import { createClient } from "@supabase/supabase-js";
import {
  SEED_CREATORS,
  SEED_SOURCE_POSTS,
  SEED_PATTERNS,
  SEED_POST_PATTERNS,
  SEED_VOICE_PROFILE,
  SEED_VOICE_EXAMPLES,
  SEED_DRAFTS,
  SEED_PUBLISHED_POSTS,
  SEED_PERFORMANCE,
  SEED_PATTERN_PERFORMANCE
} from "../../src/lib/data/seed-data";

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceKey) {
    console.log(
      "No Supabase project configured (NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set).\n" +
        "DEMO_MODE already serves this exact seed dataset from an in-memory store - nothing to do.\n" +
        "Configure a real Supabase project (see .env.example) to seed a hosted database instead."
    );
    return;
  }

  const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });

  console.log("Seeding creators...");
  await upsert(supabase, "creators", SEED_CREATORS);

  console.log("Seeding content_patterns...");
  await upsert(supabase, "content_patterns", SEED_PATTERNS);

  console.log("Seeding source_posts...");
  await upsert(
    supabase,
    "source_posts",
    SEED_SOURCE_POSTS.map(({ patternIds: _patternIds, ...post }) => post)
  );

  console.log("Seeding post_patterns...");
  await upsert(supabase, "post_patterns", SEED_POST_PATTERNS);

  console.log("Seeding voice_profiles...");
  await upsert(supabase, "voice_profiles", [SEED_VOICE_PROFILE]);

  console.log("Seeding voice_examples...");
  await upsert(supabase, "voice_examples", SEED_VOICE_EXAMPLES);

  console.log("Seeding drafts...");
  await upsert(supabase, "drafts", SEED_DRAFTS);

  console.log("Seeding published_posts...");
  await upsert(
    supabase,
    "published_posts",
    SEED_PUBLISHED_POSTS.map(({ patternId: _p, topic: _t, audience: _a, ...post }) => post)
  );

  console.log("Seeding post_performance...");
  await upsert(supabase, "post_performance", SEED_PERFORMANCE);

  console.log("Seeding pattern_performance...");
  await upsert(supabase, "pattern_performance", SEED_PATTERN_PERFORMANCE);

  console.log("Done. Note: embeddings are NOT generated by this script - run the app with a real");
  console.log("EMBEDDING_PROVIDER configured and re-save records to populate embedding columns.");
}

async function upsert(
  // Untyped on purpose: this script has no generated Database type to hand
  // createClient<Database>(), and it only ever runs ad hoc against a real
  // Supabase project - not part of the app's type-checked runtime path.
  supabase: any,
  table: string,
  rows: Record<string, unknown>[]
) {
  if (rows.length === 0) return;
  const { error } = await supabase.from(table).upsert(rows);
  if (error) {
    console.error(`Failed to seed ${table}:`, error.message);
    throw error;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
