/**
 * npm run seed
 *
 * Pushes the fictional seed dataset into a real Supabase project. Only
 * useful once you've set DEMO_MODE=false and configured
 * NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY - without those, the
 * app already runs against the same seed data in-memory (see
 * src/lib/data/memory-store.ts) and this script has nothing to do.
 *
 * This requires network access to Supabase from wherever it's run. If
 * that's not available (e.g. a sandboxed environment with restricted
 * egress), use GET /api/admin/seed on the deployed app instead - it does
 * the exact same thing via a browser hitting your live app, which has real
 * internet access. See src/lib/data/seed-supabase.ts for the shared logic.
 */
import { createClient } from "@supabase/supabase-js";
import { seedSupabase } from "../../src/lib/data/seed-supabase";

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceKey) {
    console.log(
      "No Supabase project configured (NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set).\n" +
        "DEMO_MODE already serves this exact seed dataset from an in-memory store - nothing to do.\n" +
        "Configure a real Supabase project (see .env.example) to seed a hosted database instead."
    );
    return;
  }

  const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });
  const results = await seedSupabase(supabase);

  for (const r of results) {
    if (r.error) console.error(`FAILED ${r.table} (${r.rows} rows): ${r.error}`);
    else console.log(`OK ${r.table}: ${r.rows} rows`);
  }

  if (results.some((r) => r.error)) {
    process.exitCode = 1;
  } else {
    console.log("\nDone. Note: embeddings are NOT generated by this script - run the app with a real");
    console.log("EMBEDDING_PROVIDER configured and re-save records to populate embedding columns.");
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
